import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pdfDir = path.resolve(__dirname, "../../storage/pdfs");

export const sanitizePdfFilename = (value) =>
  `${value}`.replace(/[^a-z0-9-_]+/gi, "-").replace(/-+/g, "-").replace(/^-|-$/g, "").toLowerCase();

const writePdf = async (filename, draw) => {
  await fs.promises.mkdir(pdfDir, { recursive: true });

  const safeFilename = `${sanitizePdfFilename(filename)}.pdf`;
  const filePath = path.join(pdfDir, safeFilename);
  const doc = new PDFDocument({ margin: 48 });
  const stream = fs.createWriteStream(filePath);

  doc.pipe(stream);
  draw(doc);
  doc.end();

  await new Promise((resolve, reject) => {
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  return `/pdfs/${safeFilename}`;
};

export const generateInvoicePdf = async ({ invoice, customer }) =>
  writePdf(`invoice-${invoice.id}`, (doc) => {
    const isDraftPending = invoice.status === "draft" && invoice.amount === 0;
    const amountDisplay = isDraftPending ? "DRAFT - Pending Amount" : `$${invoice.amount.toFixed(2)}`;

    doc.fontSize(22).text(isDraftPending ? "NxtBiz Invoice (DRAFT)" : "NxtBiz Invoice");
    doc.moveDown();
    doc.fontSize(12).text(`Invoice ID: ${invoice.id}`);
    doc.text(`Customer: ${customer?.name ?? "Unknown customer"}`);
    doc.text(`Due date: ${invoice.dueDate.toISOString().slice(0, 10)}`);
    doc.text(`Amount due: ${amountDisplay}`);
    doc.moveDown();
    doc.text("Line Items");
    invoice.lineItems.forEach((item) => {
      doc.text(`- ${item.description}: ${item.quantity} x $${item.unitPrice.toFixed(2)}`);
    });
    doc.moveDown();
    doc.text("Generated by NxtBiz operations automation.");
  });

export const generateReportPdf = async ({ report }) =>
  writePdf(`report-${report.id}`, (doc) => {
    doc.fontSize(22).text(report.title);
    doc.moveDown();
    doc.fontSize(12).text(report.summary || "No summary provided.");
    doc.moveDown();
    doc.fontSize(14).text("Metrics");
    Object.entries(report.metrics || {}).forEach(([key, value]) => {
      doc.fontSize(12).text(`${key}: ${value}`);
    });
    doc.moveDown();
    doc.fontSize(14).text("Recommendations");
    report.recommendations.forEach((recommendation) => {
      doc.fontSize(12).text(`- ${recommendation}`);
    });
  });
